name: Destroy Cloud CA
on:
  workflow_dispatch:
permissions:
  contents: read
env:
  TF_VAR_cloud_app_sso_arn: ${{ secrets.CLOUD_APP_SSO_ARN }} # delete if not needed
  TF_VAR_cloud_app_user_arn: ${{ secrets.CLOUD_APP_USER_ARN }} # delete if not needed
  TF_VAR_elb_service_role_arn: ${{ secrets.ELB_SERVICE_ROLE_ARN }} # delete if not needed
  TF_VAR_slack_token: ${{ secrets.SLACK_TOKEN }} # delete if not needed

jobs:
  terraform_destroy:
    name: Terraform destroy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - name: Terraform setup
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4
        with:
          terraform_version: 1.12.2

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Clone CA Terraform Module
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: serverless-ca/terraform-aws-ca
          token: ${{secrets.GH_TOKEN}}
          path: terraform-modules

      - name: Configure AWS Credentials - Dev
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN}}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform initialise
        run: >
          terraform init 
          -backend-config=bucket=${{ secrets.TERRAFORM_STATE_BUCKET}} 
          -backend-config=key=${{ secrets.TERRAFORM_STATE_KEY}} 
          -backend-config=region=${{ secrets.TERRAFORM_STATE_REGION}}

      - name: terraform destroy
        run: terraform destroy -auto-approve